alerting:
  slack:
    webhook-url: "${SLACK_WEBHOOK_URL}"
    default-alert:
      failure-threshold: 3
      send-on-resolved: true
      send-on-recovery: true

storage:
  type: sqlite
  path: /data/data.db

endpoints:
  - name: Portfolio
    group: Personal
    url: "https://portfolio.accoumar.fr/"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1500"
    alerts:
      - type: slack
        description: "🚨 Portfolio website is down or slow."

  - name: Blog
    group: Personal
    url: "https://blog.accoumar.fr/"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1500"
    alerts:
      - type: slack
        description: "🚨 Blog website is down or slow."

  - name: n8n
    group: Personal
    url: "https://n8n.accoumar.fr/"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1500"
    alerts:
      - type: slack
        description: "🚨 n8n website is down or slow."

  - name: CrossFilterUI
    group: Personal
    url: "https://crossfilterui.accoumar.fr/"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1500"
    alerts:
      - type: slack
        description: "🚨 CrossFilterUI website is down or slow."
